steps:
  # Build the Docker image with production FastAPI wrapper
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.production'
      - '-t'
      - 'gcr.io/quendoo-mcp-prod/quendoo-mcp-multitenant:latest'
      - '.'

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/quendoo-mcp-prod/quendoo-mcp-multitenant:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'quendoo-mcp-multitenant'
      - '--image'
      - 'gcr.io/quendoo-mcp-prod/quendoo-mcp-multitenant:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'MCP_TRANSPORT=sse'

images:
  - 'gcr.io/quendoo-mcp-prod/quendoo-mcp-multitenant:latest'
