steps:
  # Build the Docker image with production FastAPI wrapper
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.production'
      - '-t'
      - 'gcr.io/quendoo-mcp-prod/quendoo-mcp-multitenant:latest'
      - '.'

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/quendoo-mcp-prod/quendoo-mcp-multitenant:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'quendoo-mcp-multitenant'
      - '--image'
      - 'gcr.io/quendoo-mcp-prod/quendoo-mcp-multitenant:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DATABASE_URL=postgresql://postgres.tjrtbhemajqwzzdzyjtc:Newestate2019%40@aws-1-eu-west-1.pooler.supabase.com:6543/postgres,JWT_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCx/hpaO4SmGLM/\nJdv3bjY8bkt97VDZneWnnS+oOhbPQGPzahp6t7MVsppxB0F+pdN5julaRNlXWHgm\nM9o1NVsaetEQfAQlWW8OPBnNc7IOoGYEYcq8wqyVxyHWKppG6ffF1I98Wt99pgiP\neBDimqpIM10WYCZDgBt75M47th5FKcS2QFPdmRQZpQAyGO878gBzf6J0XVOeP9bd\n4XoKhEGxQZmzSgZIEbWQayh7bnWHE+K3QBbIpcIehNgw/3IWSEsjIpFceJe7Iyqb\nlDa4pez/O/VnHoWgT4msvIkKNRGP9CdVs26EHnnW4qKE9kQKTCYF9JHbtI8UGUww\nGLa4ZwXTAgMBAAECggEACN1e8p+EO8F/K+X2zpvul5Pmrp7jJ/N1PKPXe8lo2Wmb\nkMP4DaSYhrwedQKngGdB4Qv9E0HakT8WvNBYTc4ae3cicm+6xSFvJoZXwqPAenoC\nmrVEI6KOdec1CDWW+XEtpeywOMFN4DQkuQCB1sddM7tbJ4IiZbo7pDABFXg8ibU1\nh2h6syjS1inT72BEoQHzGS8jajlZ4WnzlhKg/FIj+mMZf5nTrFV0wBamVnEk6bKj\ngYVmACOKp18qQBpM+LIV+x4MdDDSgvX/AApiFh9eu3Tt/UN0WkvC8luPUW7tARIj\nXUTP/19KGEpupn23DzVVckL/fXuteXLRA6J2BiMcAQKBgQDkOWJjvfEIcX0AB3sd\ndRncvT+9e4Vu4KbnU3y85XzwZTIwDWgZplS2gGrAZUmYDIskRkL/vrfEF7fBKvIu\nlE31pGv/m3nLlNoR5mso1ulsccnwsxeUQOWpUk6CmgrQLFrH4CdvACyTk2ME8iP9\nhJdSBUohjMtMkxWlwasvZtqXCQKBgQDHp7CYn2FM/cBOgOAD320mmndgeRjTlSPW\ncM7aFvq+vvTBR4EKRCjVN0Oq0wwhpd0KqgQHi7DpF5mDAKzdoCthAiltL6PrObJa\nvnaw+rhbT6sAxDpEX2eVNOZdQyBWuP/tT0IsXRlQVfeKrXWa147Q5aaJXllXb2w9\nxL5W9Tlw+wKBgEseRC82Ppab3BvdWn2IpJmOROOWO4YSNX1gcmcuVeA+PrWoRAJl\nR+7F990ZuY5tWoL3CWhqGsxVTisreokwUTSwCMgaIY2LkfdgUxcfHbePAHvURseK\nUM1ZhPPhxftdDghJ1FDpysJMOcRP+t6f/LqHeS3vzJ6IrxBe3Xx9qycZAoGBAJFq\nhIgVBXRjGU7UNNT9RW2pcas1aCyq4ohMb4yO0iBdyrx/jO/iRu9Mqh9gSeSz/rPG\nstqgFsEe7DNrKXzeLNoiDfQ1j6lCw7GuKZqrcd0nwH/1bA7igfo9pk9lFce0RMse\nQC85u7c0dfBueErIF3/01AAXVPEG+YpfotaJE0ZDAoGBAK2Oxr9Ad624bdXu6rbC\nbBsRYcGO4xK//pD987vhU43Dnyiop6X9W4RgLacxmPxBP03SRaiUfP6OolO4gMR0\n9XwiakeknQAKsDjbcjikiuWH632ZonnBQW5u7wl5eiToFk6rU4aABuWs1KOFH5KJ\nbNunLZxGnnSTWGIKH2xFq1WP\n-----END PRIVATE KEY-----,MCP_TRANSPORT=sse,BASE_URL=https://quendoo-mcp-multitenant-851052272168.us-central1.run.app,JWT_ISSUER=https://quendoo-mcp-multitenant-851052272168.us-central1.run.app'

images:
  - 'gcr.io/quendoo-mcp-prod/quendoo-mcp-multitenant:latest'
