steps:
  # Build OAuth server image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.oauth'
      - '-t'
      - 'gcr.io/quendoo-mcp-prod/quendoo-oauth-server:latest'
      - '.'

  # Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/quendoo-mcp-prod/quendoo-oauth-server:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'quendoo-oauth-server'
      - '--image'
      - 'gcr.io/quendoo-mcp-prod/quendoo-oauth-server:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/quendoo-mcp-prod/quendoo-oauth-server:latest'
